package Base.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.typesystem.inference.EquationInfo;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.builder.SNodeBuilder;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class typeof_INumericLiteral_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_INumericLiteral_InferenceRule() {
  }
  public void applyRule(final SNode numericLiteral, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    {
      SNode _nodeToCheck_1029348928467 = numericLiteral;
      EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:76c6972a-64e3-40d5-8957-3606fbda194a(Base.typesystem)", "2207109450940936522", 0, null);
      typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:76c6972a-64e3-40d5-8957-3606fbda194a(Base.typesystem)", "2207109450940935236", true), (SNode) createNumberType_bh6389_a0a0b(), _info_12389875345);
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.INumericLiteral$KH;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }
  private static SNode createNumberType_bh6389_a0a0b() {
    SNodeBuilder n0 = new SNodeBuilder().init(CONCEPTS.NumberType$oN);
    return n0.getResult();
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept INumericLiteral$KH = MetaAdapterFactory.getInterfaceConcept(0x29b980d162104d27L, 0x916e07bc0552ea93L, 0x1ea13a5a13bdd0bbL, "Base.structure.INumericLiteral");
    /*package*/ static final SConcept NumberType$oN = MetaAdapterFactory.getConcept(0x29b980d162104d27L, 0x916e07bc0552ea93L, 0x3d822ec454602e77L, "Base.structure.NumberType");
  }
}
