package DataMapping.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_CSVQuoteChar extends EnumerationDescriptorBase {

  public EnumerationDescriptor_CSVQuoteChar() {
    super(0x22a6c585e3ba46bcL, 0x922caa7eb0f6869bL, 0xd79bf50eeafe6aeL, "CSVQuoteChar", "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/971017548997846702");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_apostrophe_0 = new EnumerationDescriptor.MemberDescriptor("apostrophe", "aposztróf (')", 0xd79bf50eeafe6afL, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/971017548997846703");
  private final EnumerationDescriptor.MemberDescriptor myMember_doubleQuotes_0 = new EnumerationDescriptor.MemberDescriptor("doubleQuotes", "idézőjel (\")", 0xd79bf50eeafe6b2L, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/971017548997846706");
  private final EnumerationDescriptor.MemberDescriptor myMember_no_0 = new EnumerationDescriptor.MemberDescriptor("no", "nincs", 0xd79bf50eeafe94fL, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/971017548997847375");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x22a6c585e3ba46bcL, 0x922caa7eb0f6869bL, 0xd79bf50eeafe6aeL, 0xd79bf50eeafe6afL, 0xd79bf50eeafe6b2L, 0xd79bf50eeafe94fL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_apostrophe_0, myMember_doubleQuotes_0, myMember_no_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_no_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "apostrophe":
        return myMember_apostrophe_0;
      case "doubleQuotes":
        return myMember_doubleQuotes_0;
      case "no":
        return myMember_no_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
