package DataMapping.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_FileEncoding extends EnumerationDescriptorBase {

  public EnumerationDescriptor_FileEncoding() {
    super(0x22a6c585e3ba46bcL, 0x922caa7eb0f6869bL, 0x72160cfe047998c9L, "FileEncoding", "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/8220772454947723465");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_UTF_8_BOM_0 = new EnumerationDescriptor.MemberDescriptor("UTF_8_BOM", "UTF-8 BOM", 0x72160cfe047998caL, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/8220772454947723466");
  private final EnumerationDescriptor.MemberDescriptor myMember_UTF_8_0 = new EnumerationDescriptor.MemberDescriptor("UTF_8", "UTF-8 BOM nélkül", 0x72160cfe04799c8eL, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/8220772454947724430");
  private final EnumerationDescriptor.MemberDescriptor myMember_UTF_16_0 = new EnumerationDescriptor.MemberDescriptor("UTF_16", "UTF-16", 0x72160cfe0479a417L, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/8220772454947726359");
  private final EnumerationDescriptor.MemberDescriptor myMember_Win_1250_0 = new EnumerationDescriptor.MemberDescriptor("Win_1250", "Windows-1250", 0x72160cfe0479a7f7L, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/8220772454947727351");
  private final EnumerationDescriptor.MemberDescriptor myMember_IBM_852_0 = new EnumerationDescriptor.MemberDescriptor("IBM_852", "OEM 852 (Latin 2)", 0x559eb217349bbef1L, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/6169564352280772337");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x22a6c585e3ba46bcL, 0x922caa7eb0f6869bL, 0x72160cfe047998c9L, 0x72160cfe047998caL, 0x72160cfe04799c8eL, 0x72160cfe0479a417L, 0x72160cfe0479a7f7L, 0x559eb217349bbef1L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_UTF_8_BOM_0, myMember_UTF_8_0, myMember_UTF_16_0, myMember_Win_1250_0, myMember_IBM_852_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "UTF_8_BOM":
        return myMember_UTF_8_BOM_0;
      case "UTF_8":
        return myMember_UTF_8_0;
      case "UTF_16":
        return myMember_UTF_16_0;
      case "Win_1250":
        return myMember_Win_1250_0;
      case "IBM_852":
        return myMember_IBM_852_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
