package DataMapping.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_JoinType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_JoinType() {
    super(0x22a6c585e3ba46bcL, 0x922caa7eb0f6869bL, 0x6c0ed9cfeda82cccL, "JoinType", "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/7786400292838845644");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Inner_0 = new EnumerationDescriptor.MemberDescriptor("Inner", "inner", 0x6c0ed9cfeda82cceL, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/7786400292838845646");
  private final EnumerationDescriptor.MemberDescriptor myMember_LeftOuter_0 = new EnumerationDescriptor.MemberDescriptor("LeftOuter", "left outer", 0x6c0ed9cfeda82ccdL, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/7786400292838845645");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x22a6c585e3ba46bcL, 0x922caa7eb0f6869bL, 0x6c0ed9cfeda82cccL, 0x6c0ed9cfeda82cceL, 0x6c0ed9cfeda82ccdL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Inner_0, myMember_LeftOuter_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_Inner_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Inner":
        return myMember_Inner_0;
      case "LeftOuter":
        return myMember_LeftOuter_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
