package DataMapping.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ThousandSeparatorEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ThousandSeparatorEnum() {
    super(0x22a6c585e3ba46bcL, 0x922caa7eb0f6869bL, 0x72160cfe047bb7c1L, "ThousandSeparatorEnum", "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/8220772454947862465");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_no_0 = new EnumerationDescriptor.MemberDescriptor("no", "nincs", 0x72160cfe047bc18cL, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/8220772454947864972");
  private final EnumerationDescriptor.MemberDescriptor myMember_comma_0 = new EnumerationDescriptor.MemberDescriptor("comma", ", <vessző>", 0x72160cfe047bb7c2L, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/8220772454947862466");
  private final EnumerationDescriptor.MemberDescriptor myMember_space_0 = new EnumerationDescriptor.MemberDescriptor("space", "  <szóköz>", 0x72160cfe047bba67L, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/8220772454947863143");
  private final EnumerationDescriptor.MemberDescriptor myMember_apostrophe_0 = new EnumerationDescriptor.MemberDescriptor("apostrophe", "' <aposztróf>", 0x72160cfe047bbf7eL, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/8220772454947864446");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x22a6c585e3ba46bcL, 0x922caa7eb0f6869bL, 0x72160cfe047bb7c1L, 0x72160cfe047bc18cL, 0x72160cfe047bb7c2L, 0x72160cfe047bba67L, 0x72160cfe047bbf7eL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_no_0, myMember_comma_0, myMember_space_0, myMember_apostrophe_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "no":
        return myMember_no_0;
      case "comma":
        return myMember_comma_0;
      case "space":
        return myMember_space_0;
      case "apostrophe":
        return myMember_apostrophe_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
