package DataMapping.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_TextAlignmentEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_TextAlignmentEnum() {
    super(0x22a6c585e3ba46bcL, 0x922caa7eb0f6869bL, 0x72160cfe04784123L, "TextAlignmentEnum", "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/8220772454947635491");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_right_0 = new EnumerationDescriptor.MemberDescriptor("right", "jobbra", 0x72160cfe04784124L, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/8220772454947635492");
  private final EnumerationDescriptor.MemberDescriptor myMember_center_0 = new EnumerationDescriptor.MemberDescriptor("center", "középre", 0x72160cfe04784362L, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/8220772454947636066");
  private final EnumerationDescriptor.MemberDescriptor myMember_left_0 = new EnumerationDescriptor.MemberDescriptor("left", "balra", 0x72160cfe047845d5L, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/8220772454947636693");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x22a6c585e3ba46bcL, 0x922caa7eb0f6869bL, 0x72160cfe04784123L, 0x72160cfe04784124L, 0x72160cfe04784362L, 0x72160cfe047845d5L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_right_0, myMember_center_0, myMember_left_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "right":
        return myMember_right_0;
      case "center":
        return myMember_center_0;
      case "left":
        return myMember_left_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
