package DataMapping.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ComparisonOperator extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ComparisonOperator() {
    super(0x22a6c585e3ba46bcL, 0x922caa7eb0f6869bL, 0x9a45cf657946840L, "ComparisonOperator", "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/694782455622953024");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_less_0 = new EnumerationDescriptor.MemberDescriptor("less", "<", 0x9a45cf657946842L, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/694782455622953026");
  private final EnumerationDescriptor.MemberDescriptor myMember_greater_0 = new EnumerationDescriptor.MemberDescriptor("greater", ">", 0x9a45cf65794684fL, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/694782455622953039");
  private final EnumerationDescriptor.MemberDescriptor myMember_not_equal_0 = new EnumerationDescriptor.MemberDescriptor("not_equal", "<>", 0x9a45cf657946841L, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/694782455622953025");
  private final EnumerationDescriptor.MemberDescriptor myMember_less_or_equal_0 = new EnumerationDescriptor.MemberDescriptor("less_or_equal", "<=", 0x9a45cf657946854L, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/694782455622953044");
  private final EnumerationDescriptor.MemberDescriptor myMember_greater_or_equal_0 = new EnumerationDescriptor.MemberDescriptor("greater_or_equal", ">=", 0x9a45cf65794685aL, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/694782455622953050");
  private final EnumerationDescriptor.MemberDescriptor myMember_equal_0 = new EnumerationDescriptor.MemberDescriptor("equal", "=", 0x9a45cf65794684bL, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/694782455622953035");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x22a6c585e3ba46bcL, 0x922caa7eb0f6869bL, 0x9a45cf657946840L, 0x9a45cf657946842L, 0x9a45cf65794684fL, 0x9a45cf657946841L, 0x9a45cf657946854L, 0x9a45cf65794685aL, 0x9a45cf65794684bL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_less_0, myMember_greater_0, myMember_not_equal_0, myMember_less_or_equal_0, myMember_greater_or_equal_0, myMember_equal_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_equal_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "less":
        return myMember_less_0;
      case "greater":
        return myMember_greater_0;
      case "not_equal":
        return myMember_not_equal_0;
      case "less_or_equal":
        return myMember_less_or_equal_0;
      case "greater_or_equal":
        return myMember_greater_or_equal_0;
      case "equal":
        return myMember_equal_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
