package DataMapping.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_HeaderType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_HeaderType() {
    super(0x22a6c585e3ba46bcL, 0x922caa7eb0f6869bL, 0x28652327d2abbL, "HeaderType", "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/710637545925307");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_no_0 = new EnumerationDescriptor.MemberDescriptor("no", "nincs", 0x28652327d2abcL, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/710637545925308");
  private final EnumerationDescriptor.MemberDescriptor myMember_name_0 = new EnumerationDescriptor.MemberDescriptor("name", "mező név", 0x28652327d2abdL, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/710637545925309");
  private final EnumerationDescriptor.MemberDescriptor myMember_description_0 = new EnumerationDescriptor.MemberDescriptor("description", "mező leírás", 0x28652327d2ac0L, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/710637545925312");
  private final EnumerationDescriptor.MemberDescriptor myMember_custom_0 = new EnumerationDescriptor.MemberDescriptor("custom", "egyedi", 0x28652327d2ac4L, "r:2d36f7b5-27c5-4304-ac9a-34504b59f0d2(DataMapping.structure)/710637545925316");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x22a6c585e3ba46bcL, 0x922caa7eb0f6869bL, 0x28652327d2abbL, 0x28652327d2abcL, 0x28652327d2abdL, 0x28652327d2ac0L, 0x28652327d2ac4L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_no_0, myMember_name_0, myMember_description_0, myMember_custom_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_name_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "no":
        return myMember_no_0;
      case "name":
        return myMember_name_0;
      case "description":
        return myMember_description_0;
      case "custom":
        return myMember_custom_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
