package DataMapping.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.typesystem.inference.EquationInfo;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class typeof_Condition_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_Condition_InferenceRule() {
  }
  public void applyRule(final SNode condition, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    {
      SNode _nodeToCheck_1029348928467 = SLinkOperations.getTarget(condition, LINKS.leftSide$dqOy);
      EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:2ccfac22-e537-4cc8-903d-e30f04953635(DataMapping.typesystem)", "2019413829186097061", 0, null);
      typeCheckingContext.createLessThanInequality((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:2ccfac22-e537-4cc8-903d-e30f04953635(DataMapping.typesystem)", "2019413829186097064", true), (SNode) typeCheckingContext.typeOf(SLinkOperations.getTarget(condition, LINKS.rightSide$NWbw), "r:2ccfac22-e537-4cc8-903d-e30f04953635(DataMapping.typesystem)", "2019413829186097069", true), false, true, _info_12389875345);
    }
    {
      SNode _nodeToCheck_1029348928467 = SLinkOperations.getTarget(condition, LINKS.rightSide$NWbw);
      EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:2ccfac22-e537-4cc8-903d-e30f04953635(DataMapping.typesystem)", "8596373292600955615", 0, null);
      typeCheckingContext.createLessThanInequality((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:2ccfac22-e537-4cc8-903d-e30f04953635(DataMapping.typesystem)", "8596373292600955632", true), (SNode) typeCheckingContext.typeOf(SLinkOperations.getTarget(condition, LINKS.leftSide$dqOy), "r:2ccfac22-e537-4cc8-903d-e30f04953635(DataMapping.typesystem)", "8596373292600957559", true), false, true, _info_12389875345);
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.SourceCondition$oV;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink leftSide$dqOy = MetaAdapterFactory.getContainmentLink(0x22a6c585e3ba46bcL, 0x922caa7eb0f6869bL, 0x28099d21881b9060L, 0x28099d2188233f0eL, "leftSide");
    /*package*/ static final SContainmentLink rightSide$NWbw = MetaAdapterFactory.getContainmentLink(0x22a6c585e3ba46bcL, 0x922caa7eb0f6869bL, 0x28099d21881b9060L, 0x28099d2188234250L, "rightSide");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept SourceCondition$oV = MetaAdapterFactory.getConcept(0x22a6c585e3ba46bcL, 0x922caa7eb0f6869bL, 0x28099d21881b9060L, "DataMapping.structure.SourceCondition");
  }
}
