package DataMapping.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.typesystem.inference.EquationInfo;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;

public class typeof_IAttributeRef_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_IAttributeRef_InferenceRule() {
  }
  public void applyRule(final SNode attributeRef, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    {
      SNode _nodeToCheck_1029348928467 = attributeRef;
      EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:2ccfac22-e537-4cc8-903d-e30f04953635(DataMapping.typesystem)", "3905948371873366071", 0, null);
      typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:2ccfac22-e537-4cc8-903d-e30f04953635(DataMapping.typesystem)", "3905948371873364745", true), (SNode) SLinkOperations.getTarget(SLinkOperations.getTarget(attributeRef, LINKS.attribute$R3A$), LINKS.type$T2Ku), _info_12389875345);
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.IAttributeRef$Hn;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink attribute$R3A$ = MetaAdapterFactory.getReferenceLink(0x22a6c585e3ba46bcL, 0x922caa7eb0f6869bL, 0x49a403aa3321cb12L, 0x49a403aa3321cb14L, "attribute");
    /*package*/ static final SContainmentLink type$T2Ku = MetaAdapterFactory.getContainmentLink(0xbe5be3d615724d96L, 0x87fbb6ad07c44926L, 0x2a3d62b653db628fL, 0x3d822ec4546232a8L, "type");
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept IAttributeRef$Hn = MetaAdapterFactory.getInterfaceConcept(0x22a6c585e3ba46bcL, 0x922caa7eb0f6869bL, 0x49a403aa3321cb12L, "DataMapping.structure.IAttributeRef");
  }
}
