package DataMapping.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;

public class MappingEmptyItem_SubstituteMenu extends SubstituteMenuBase {
  public MappingEmptyItem_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for " + "MappingEmptyItem", new SNodePointer("r:fca1f299-8f6d-4e3d-9e38-79f214201296(DataMapping.editor)", "2671830247026761369")));
  }

}
