package DataSource.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_MethodType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_MethodType() {
    super(0xbe5be3d615724d96L, 0x87fbb6ad07c44926L, 0x4a2401a090a5025fL, "MethodType", "r:21f953e6-cc0c-476c-8497-96314bf48f7f(DataSource.structure)/5342396847101379167");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Get_0 = new EnumerationDescriptor.MemberDescriptor("Get", "Get", 0x4a2401a090a50262L, "r:21f953e6-cc0c-476c-8497-96314bf48f7f(DataSource.structure)/5342396847101379170");
  private final EnumerationDescriptor.MemberDescriptor myMember_Post_0 = new EnumerationDescriptor.MemberDescriptor("Post", "Post", 0x4a2401a090a50266L, "r:21f953e6-cc0c-476c-8497-96314bf48f7f(DataSource.structure)/5342396847101379174");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xbe5be3d615724d96L, 0x87fbb6ad07c44926L, 0x4a2401a090a5025fL, 0x4a2401a090a50262L, 0x4a2401a090a50266L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Get_0, myMember_Post_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_Get_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Get":
        return myMember_Get_0;
      case "Post":
        return myMember_Post_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
